name: Elixir CI
env:
    DATABASE_NAME: entity_db
    DATABASE_USERNAME: test_user
    DATABASE_PASSWORD: password
    DATABASE_HOST: localhost

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: ${{ env.DATABASE_NAME }}
          MYSQL_USER: ${{ env.DATABASE_USERNAME }}
          MYSQL_PASSWORD: ${{ env.DATABASE_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ env.DATABASE_PASSWORD }}
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-elixir@v1
      with:
        elixir-version: '1.15.2' # Define the Elixir version
        otp-version: '26.0'      # Define the Erlang/OTP version
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Debug MySQL Connection
      run: |
        sudo apt-get update
        sudo apt-get install -y netcat
        nc -vz ${{ env.DATABASE_HOST }} 3306
        
    - name: Install dependencies and Test installation
      run: |
          mix deps.get
          iex -S mix 
          
    - name: Run tests
      run: |
         mix --version
         mix test
